/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChartConfiguration } from "chart.js";
export namespace Components {
    interface TrendsChart {
        "config": ChartConfiguration;
    }
}
declare global {
    interface HTMLTrendsChartElement extends Components.TrendsChart, HTMLStencilElement {
    }
    var HTMLTrendsChartElement: {
        prototype: HTMLTrendsChartElement;
        new (): HTMLTrendsChartElement;
    };
    interface HTMLElementTagNameMap {
        "trends-chart": HTMLTrendsChartElement;
    }
}
declare namespace LocalJSX {
    interface TrendsChart {
        "config"?: ChartConfiguration;
    }
    interface IntrinsicElements {
        "trends-chart": TrendsChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "trends-chart": LocalJSX.TrendsChart & JSXBase.HTMLAttributes<HTMLTrendsChartElement>;
        }
    }
}
